spring.application.name=room-booking-be
spring.datasource.url=jdbc:postgresql://103.77.241.6:6432/room_booking
spring.datasource.username=hcmut
spring.datasource.password=toiyeuhcmut
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect